### ISSUE TITLE
Two problems

### ISSUE THREAD

**Issue by ravenxrz** [ericaloha/L2SM#2]
I found two problems after doing some simple tests.
1. when I run the default db_bench with benchamrks='fillrandom,readrandom' flag, it was corrupted.
![image](https://user-images.githubusercontent.com/44746032/147093309-a451dd42-b671-46ad-93ab-02941161b56f.png)
2. Couldn't find the value inserted before. demo test code is below:
```
  std::unordered_map<std::string, std::string> model;
  char key[32];
  char value[1000];
  ReadOptions ro;
  ro.fill_cache = false;
  std::string model_value;
  std::string get_value;
  for (int i = 0; i < 1000 * 1000 * 10; i++) {
    int rd_num = rand();
    snprintf(key, sizeof(key), "%016d", rd_num);
    model[key] = value;
    db->Put(WriteOptions(), key, Slice(value, sizeof(value)));
  }
  for (const auto &kv : model) {
    Status s = db->Get(ro, kv.first, &get_value);
    ASSERT_TRUE(s.ok());  // assert fire !!
  }
```
Is there anything I missed?

**Comment by ericaloha** [comment]
For Issue#1: I remember that once I implemented another benchmark type, which works fine. You can touch it at the de_bench code file. And I adopted some time stamp collection and process killing, maybe they lead to the segment fault.

For Issue#2: I did not face such an issue before. I guess it was caused by the configuration of SST-Log. I directly modified the read logic, you can touch the codes to find out.

**Comment by ravenxrz** [comment]
Thank you for the reply.  I will check the configuration later.
